import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { readMedia, mimeFor } from "@/lib/research/media-store";
import { marked } from "marked";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 120;

function safeFileName(title: string): string {
  return (
    title
      .replace(/[^\w\s-]/g, "")
      .trim()
      .replace(/\s+/g, "-")
      .slice(0, 80)
      .toLowerCase() || "research-essay"
  );
}

async function buildStandaloneHtml(
  title: string,
  markdown: string,
  sources: SourceLike[]
): Promise<string> {
  // embed local media as base64 so the file is fully self-contained
  let md = markdown;
  const mediaMatches = [...md.matchAll(/!\[([^\]]*)\]\((\/api\/media\/[^)\s]+)\)/g)];
  for (const m of mediaMatches) {
    const name = m[2].split("/").pop() ?? "";
    const data = await readMedia(name.split("?")[0]);
    if (data) {
      const mime = mimeFor(name);
      md = md.replace(
        m[0],
        `![${m[1]}](data:${mime};base64,${data.toString("base64")})`
      );
    }
  }

  const bodyHtml = await marked.parse(md);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title.replace(/[<>&]/g, "")}</title>
<style>
  :root { --ink:#1c1917; --paper:#fafaf9; --accent:#b45309; --line:#e7e5e4; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--paper); color:var(--ink);
    font-family: Georgia,'Times New Roman',serif; line-height:1.75; }
  .page { max-width: 860px; margin: 0 auto; padding: 48px 28px 80px; }
  h1 { font-size: 2.4rem; line-height:1.2; margin: 0 0 8px; }
  h2 { font-size: 1.45rem; margin-top: 2.2em; border-bottom: 1px solid var(--line); padding-bottom: 6px; }
  h3 { font-size: 1.15rem; margin-top: 1.8em; }
  p { margin: 1.1em 0; }
  img { max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 10px; box-shadow: 0 4px 18px rgba(28,25,23,.14); }
  figcaption, .cap { text-align:center; color:#78716c; font-style: italic; font-size:.9rem; margin-top:-12px; }
  blockquote { border-left: 3px solid var(--accent); margin: 1.4em 0; padding: .2em 1.2em; color:#57534e; background:#fff; border-radius: 0 8px 8px 0;}
  code { background:#f5f5f4; padding: 2px 6px; border-radius:4px; font-size:.9em;}
  a { color: var(--accent); }
  ul { padding-left: 1.4em; }
  .meta { color:#78716c; font-family: ui-sans-serif,system-ui,sans-serif; font-size:.95rem; margin-bottom: 32px; }
  .ref { font-family: ui-sans-serif,system-ui,sans-serif; font-size:.92rem; }
  footer { margin-top: 60px; color:#a8a29e; font-family: ui-sans-serif,system-ui,sans-serif; font-size:.8rem; text-align:center; border-top:1px solid var(--line); padding-top:16px;}
  @media print { body { background:#fff; } .page { padding: 0; } }
</style>
</head>
<body>
<div class="page">
${bodyHtml}
<footer>Generated by AI Researcher Pro — deep research with real sources &amp; downloadable imagery</footer>
</div>
</body>
</html>`;
}

interface SourceLike {
  id: string;
  title: string;
  url: string;
}

export async function GET(req: NextRequest) {
  const sessionId = req.nextUrl.searchParams.get("sessionId");
  const format = req.nextUrl.searchParams.get("format") ?? "html";
  if (!sessionId) {
    return Response.json({ error: "sessionId is required" }, { status: 400 });
  }
  const session = await db.researchSession.findUnique({
    where: { id: sessionId },
  });
  if (!session || !session.markdown) {
    return Response.json(
      { error: "Session not found or has no essay" },
      { status: 404 }
    );
  }

  const title = session.title ?? session.topic;
  const base = safeFileName(title);

  if (format === "md") {
    let md = session.markdown;
    const base2 = `${req.nextUrl.origin}`;
    md = md.replace(/\]\((\/api\/media\/[^)\s]+)\)/g, `](${base2}$1)`);
    return new Response(md, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="${base}.md"`,
      },
    });
  }

  let sources: SourceLike[] = [];
  try {
    sources = JSON.parse(session.sourcesJson ?? "[]");
  } catch {
    sources = [];
  }

  const html = await buildStandaloneHtml(title, session.markdown, sources);
  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${base}.html"`,
    },
  });
}
